# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SETTING(object):
    def setupUi(self, SETTING):
        SETTING.setObjectName("SETTING")
        SETTING.resize(370, 329)
        SETTING.setMinimumSize(QtCore.QSize(318, 280))
        SETTING.setMaximumSize(QtCore.QSize(370, 329))
        SETTING.setStyleSheet("QRadioButton{\n"
"    color: rgb(153, 193, 241);\n"
"}\n"
"QWidget{\n"
"    color: rgb(153, 193, 241);\n"
"    background-color: #071e26;\n"
"}\n"
"*{\n"
"    border-radius: 10px;\n"
"}")
        SETTING.setInputMethodHints(QtCore.Qt.ImhNone)
        self.horizontalLayout = QtWidgets.QHBoxLayout(SETTING)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mode = QtWidgets.QFrame(SETTING)
        self.mode.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mode.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mode.setObjectName("mode")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mode)
        self.verticalLayout.setContentsMargins(5, 0, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.mode)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.followButton = QtWidgets.QRadioButton(self.mode)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.followButton.setFont(font)
        self.followButton.setObjectName("followButton")
        self.verticalLayout.addWidget(self.followButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.fpvButton = QtWidgets.QRadioButton(self.mode)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.fpvButton.setFont(font)
        self.fpvButton.setObjectName("fpvButton")
        self.verticalLayout.addWidget(self.fpvButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lockButton = QtWidgets.QRadioButton(self.mode)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lockButton.setFont(font)
        self.lockButton.setObjectName("lockButton")
        self.verticalLayout.addWidget(self.lockButton, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.horizontalLayout.addWidget(self.mode)
        self.frame_2 = QtWidgets.QFrame(SETTING)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setContentsMargins(5, 9, 5, 5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.Gimbal_ver = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Gimbal_ver.sizePolicy().hasHeightForWidth())
        self.Gimbal_ver.setSizePolicy(sizePolicy)
        self.Gimbal_ver.setText("")
        self.Gimbal_ver.setObjectName("Gimbal_ver")
        self.verticalLayout_2.addWidget(self.Gimbal_ver, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.Zoom_ver = QtWidgets.QLabel(self.frame_2)
        self.Zoom_ver.setText("")
        self.Zoom_ver.setObjectName("Zoom_ver")
        self.verticalLayout_2.addWidget(self.Zoom_ver, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(SETTING)
        QtCore.QMetaObject.connectSlotsByName(SETTING)

    def retranslateUi(self, SETTING):
        _translate = QtCore.QCoreApplication.translate
        SETTING.setWindowTitle(_translate("SETTING", "SETTING"))
        self.label.setText(_translate("SETTING", "SET MODE"))
        self.followButton.setText(_translate("SETTING", "FOLLOW MODE"))
        self.fpvButton.setText(_translate("SETTING", "FPV MODE"))
        self.lockButton.setText(_translate("SETTING", "LOCK MODE"))
        self.label_2.setText(_translate("SETTING", "  VERSION"))
        self.label_3.setText(_translate("SETTING", "Gimbal_ver: "))
        self.label_4.setText(_translate("SETTING", "Zoom_ver:"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SETTING = QtWidgets.QWidget()
    ui = Ui_SETTING()
    ui.setupUi(SETTING)
    SETTING.show()
    sys.exit(app.exec_())
