# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gimbal.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(221, 191)
        Form.setMinimumSize(QtCore.QSize(221, 191))
        Form.setMaximumSize(QtCore.QSize(221, 191))
        Form.setStyleSheet("background-color: #071e26;\n"
"border-radius : 10px;")
        self.control = QtWidgets.QFrame(Form)
        self.control.setGeometry(QtCore.QRect(10, 10, 201, 171))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control.sizePolicy().hasHeightForWidth())
        self.control.setSizePolicy(sizePolicy)
        self.control.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control.setObjectName("control")
        self.DOWN = QtWidgets.QPushButton(self.control)
        self.DOWN.setGeometry(QtCore.QRect(70, 120, 61, 51))
        self.DOWN.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/feather (1)/arrow-down-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.DOWN.setIcon(icon)
        self.DOWN.setIconSize(QtCore.QSize(40, 40))
        self.DOWN.setObjectName("DOWN")
        self.UP = QtWidgets.QPushButton(self.control)
        self.UP.setGeometry(QtCore.QRect(70, 0, 61, 41))
        self.UP.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/feather (1)/arrow-up-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.UP.setIcon(icon1)
        self.UP.setIconSize(QtCore.QSize(40, 40))
        self.UP.setObjectName("UP")
        self.CENTER = QtWidgets.QPushButton(self.control)
        self.CENTER.setGeometry(QtCore.QRect(70, 60, 61, 41))
        self.CENTER.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/feather (1)/crosshair.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CENTER.setIcon(icon2)
        self.CENTER.setIconSize(QtCore.QSize(40, 40))
        self.CENTER.setObjectName("CENTER")
        self.RIGHT = QtWidgets.QPushButton(self.control)
        self.RIGHT.setGeometry(QtCore.QRect(150, 60, 51, 41))
        self.RIGHT.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/feather (1)/arrow-right-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RIGHT.setIcon(icon3)
        self.RIGHT.setIconSize(QtCore.QSize(40, 40))
        self.RIGHT.setObjectName("RIGHT")
        self.LEFT = QtWidgets.QPushButton(self.control)
        self.LEFT.setGeometry(QtCore.QRect(0, 60, 51, 41))
        self.LEFT.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/feather (1)/arrow-left-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.LEFT.setIcon(icon4)
        self.LEFT.setIconSize(QtCore.QSize(40, 40))
        self.LEFT.setObjectName("LEFT")
        self.Straigh = QtWidgets.QPushButton(self.control)
        self.Straigh.setGeometry(QtCore.QRect(10, 120, 51, 41))
        self.Straigh.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(119, 118, 123);")
        self.Straigh.setObjectName("Straigh")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "CONTROL"))
        self.Straigh.setText(_translate("Form", "90!"))
import icon_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
